version: '3.8'

services:
  db:
    container_name: music-db
    image: postgres:15.2-alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
  backend:
    container_name: music-api
    build:
      context: ./backend
    depends_on:
      - db
    restart: unless-stopped
    ports:
      - '${PORT}:80'
    environment:
      - PORT=${PORT}
      - POSTGRES_HOST=db
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - PRIVATE_KEY=${PRIVATE_KEY}
      - EMAIL_DEFAULT_FROM=${EMAIL_DEFAULT_FROM}
      - EMAIL_TRANSPORT=${EMAIL_TRANSPORT}