name: GitHub Actions Demo
on: 
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
      steps:
        - name: Собираем образ
          uses: isbang/compose-action@v1.4.1
          with:
            compose-file: "./docker-compose.yml"
            down-flags: "--volumes"
            services: |
              db
              backend
