name: Deploy to GitHub Docker registry
on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: 'backend'
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          registry: ghcr.io
          name: ZetHange/music-rest-nest.js/backend
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
